### ISSUE TITLE
素晴らしい改良をありがとうございます

### ISSUE THREAD

**Issue by gongqi-zhen** [dnobori/DN-Win32DiskImagerRenewal#1]
(Issuesではなく、ただの感想です。)

アプリ利用者のストレス・システム管理者の狼ばいも無くなり
昨今のPC環境にも適応する素晴らしい改良ですね。

確認すれば当然のことだよね。と言えることですが

あえて補足するならば
> 3 は、単に登が自分のデジタル証明書でデジタル署名しただけである。
デジタル署名の有効期限は2024/03/12までだから、期限を認識して使ってください。

(IPA-CyberLabでデジタル署名できないのかな)

> 1 は、単に Google Drive との相性により生じるエラーを無視し、エラーメッセージも表示しないようにした。

エラーはこんな感じで修正してるよ。
https://github.com/dnobori/DN-Win32DiskImagerRenewal/commit/fc35c86cc28a2b06c086d31ad2f4dcad14852464#diff-41e722a29c12bc2290c75b8114dc9e91fe6cc1e517a9b387b3b10ebb80855db8

とすれば、より辿るための手がかりとなるのでしょうか。

オープンソースの力を借りて、利用者目線でこんな改良を加えたらユーザにとても有益だし、システム管理者にはこんな行動をしてほしいという期待とdnoboriさんが感じてられる危惧のようなものを感じました。日々、少しずつ積んでいくしかないですね。

**Comment by dnobori** [comment]
ご意見ありがとうございます。


> デジタル署名の有効期限は2024/03/12までだから、期限を認識して使ってください。  


これは、タイムスタンプ署名を施してあるので、デジタル署名の証明書の期限が切れても問題無いと思います。

**Comment by gongqi-zhen** [comment]
> これは、タイムスタンプ署名を施してあるので、デジタル署名の証明書の期限が切れても問題無いと思います。

理解が深まりました、説明ありがとうございます。
